version: '3.8'

services:
    rabbitmq:
        image: 'rabbitmq:3.8-management-alpine'
        container_name: sensors-rabbitmq
        hostname: rabbitmq
        restart: no
        ports:
            - '15672:15672'
            - '5672:5672'
        volumes:
            - './rabbitmq_data:/var/lib/rabbitmq/mnesia'
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
        networks:
            - sensors
    mongodb:
        container_name: sensors-mongodb
        image: mongo:latest
        restart: always
        ports:
            - 27017:27017
        volumes:
            - ./docker/mongodb/data:/data/db
        networks:
            - sensors
networks:
    sensors:
        driver: bridge
